/**
 * Greek labels and reading order for the visual editor's fields. Every field is
 * generated from a section's content (see derive.ts); these name the keys.
 */

export const FIELD_LABELS: Record<string, string> = {
  a: "Απάντηση",
  accent: "Τονισμένο κείμενο",
  activities: "Δραστηριότητες",
  address: "Διεύθυνση",
  adopted: "Υιοθετημένες",
  alt: "Εναλλακτικό κείμενο",
  author: "Συντάκτης",
  avatar: "Φωτογραφία",
  awards: "Βραβεία",
  breadcrumb: "Διαδρομή (breadcrumb)",
  certificates: "Πιστοποιητικά",
  awardsCta: "Κουμπί βραβείων",
  badge: "Σήμα",
  badges: "Σήματα",
  benefits: "Οφέλη",
  body: "Κείμενο",
  cards: "Κάρτες",
  category: "Κατηγορία",
  children: "Υπομενού",
  closing: "Κλείσιμο",
  code: "Κωδικός",
  columns: "Στήλες",
  company: "Εταιρεία",
  consentLink: "Σύνδεσμος συγκατάθεσης",
  consentPost: "Συγκατάθεση — μετά",
  consentPre: "Συγκατάθεση — πριν",
  contact: "Επικοινωνία",
  cta: "Κουμπί",
  ctaLabel: "Κείμενο κουμπιού",
  ctaPrimary: "Κύριο κουμπί",
  ctaSecondary: "Δεύτερο κουμπί",
  cyprusAlt: "Κείμενο λογότυπου Κύπρου",
  description: "Περιγραφή",
  email: "Email",
  embedSrc: "Διεύθυνση ενσωμάτωσης",
  emphasis: "Έμφαση",
  euAlt: "Κείμενο λογότυπου ΕΕ",
  event: "Διοργάνωση",
  excerpt: "Περίληψη",
  eyebrow: "Υπέρτιτλος",
  featured: "Προβεβλημένο",
  firstName: "Όνομα",
  funding: "Χρηματοδότηση",
  gallery: "Γκαλερί",
  groups: "Ομάδες",
  h: "Ύψος",
  handle: "Προϊόν (handle)",
  heading: "Επικεφαλίδα",
  headingLines: "Γραμμές επικεφαλίδας",
  highlights: "Σημεία",
  hook: "Εισαγωγική φράση",
  hours: "Ωράριο",
  href: "Σύνδεσμος",
  icon: "Εικονίδιο",
  id: "Αναγνωριστικό",
  image: "Εικόνα",
  imageAlt: "Εναλλακτικό κείμενο εικόνας",
  imageClass: "Στοίχιση εικόνας",
  images: "Εικόνες",
  impact: "Αντίκτυπος",
  impactHeading: "Επικεφαλίδα αντίκτυπου",
  intro: "Εισαγωγή",
  items: "Στοιχεία",
  label: "Ετικέτα",
  lastName: "Επώνυμο",
  lastUpdated: "Τελευταία ενημέρωση",
  lead: "Εισαγωγή",
  left: "Θέση — οριζόντια (υπολογιστής)",
  legal: "Νομικό κείμενο",
  legalBrand: "Εταιρεία (υποσέλιδο)",
  legalBrandHref: "Σύνδεσμος εταιρείας",
  lines: "Γραμμές",
  link: "Σύνδεσμος",
  linkHref: "Σύνδεσμος",
  linkLabel: "Κείμενο συνδέσμου",
  links: "Σύνδεσμοι",
  logos: "Λογότυπα",
  mLeft: "Θέση — οριζόντια (κινητό)",
  mTop: "Θέση — κάθετη (κινητό)",
  members: "Μέλη",
  message: "Μήνυμα",
  meta: "SEO",
  name: "Όνομα",
  next: "Επόμενο",
  note: "Σημείωση",
  num: "Αριθμός",
  ofGoal: "Του στόχου",
  openLabel: "Κείμενο ανοίγματος",
  org: "Οργανισμός",
  paragraphs: "Παράγραφοι",
  pdfEn: "PDF (αγγλικά)",
  pdfGr: "PDF (ελληνικά)",
  phone: "Τηλέφωνο",
  phoneHref: "Τηλέφωνο (σύνδεσμος)",
  phoneShort: "Τηλέφωνο (σύντομο)",
  photo: "Φωτογραφία",
  pills: "Ετικέτες",
  placement: "Άνοιγμα κάρτας (πάνω/κάτω)",
  policies: "Πολιτικές",
  prev: "Προηγούμενο",
  price: "Τιμή",
  prices: "Τιμές στη φωτογραφία",
  primary: "Κύριο",
  product: "Προϊόν",
  products: "Προϊόντα",
  q: "Ερώτηση",
  quote: "Μαρτυρία",
  rating: "Βαθμολογία",
  remainingPost: "Υπόλοιπες — μετά",
  remainingPre: "Υπόλοιπες — πριν",
  requiredNote: "Σημείωση υποχρεωτικών",
  reversed: "Αντεστραμμένη διάταξη",
  reviews: "Κριτικές",
  right: "Δεξιά κάρτα",
  role: "Ιδιότητα",
  secondary: "Δεύτερο",
  sections: "Ενότητες",
  seo: "SEO",
  size: "Μέγεθος",
  slides: "Διαφάνειες",
  slug: "Αναγνωριστικό URL",
  social: "Κοινωνικά δίκτυα",
  src: "Εικόνα",
  stat: "Αριθμός",
  stats: "Αριθμοί",
  steps: "Βήματα",
  sub: "Υπότιτλος",
  subject: "Θέμα",
  submit: "Κουμπί αποστολής",
  tagline: "Σύνθημα",
  taglineAccent: "Σύνθημα — τονισμένο",
  taglinePost: "Σύνθημα — μετά",
  taglinePre: "Σύνθημα — πριν",
  tel: "Τηλέφωνο",
  text: "Κείμενο",
  thaleiaAlt: "Κείμενο λογότυπου ΘΑλΕΙΑ",
  thankYou: "Μήνυμα ευχαριστίας",
  tier: "Διάκριση",
  title: "Τίτλος",
  top: "Θέση — κάθετη (υπολογιστής)",
  unit: "Μονάδα",
  value: "Τιμή",
  values: "Αξίες",
  w: "Πλάτος",
  whyHeading: "Επικεφαλίδα «Γιατί»",
  wordmark: "Λογότυπο",
  wordmarkAlt: "Κείμενο λογότυπου",
  year: "Έτος",
}

/** Labels for keys that name a group rather than a value — `left` is a card on
 *  the home hero but a pin position on the flatlay. */
const GROUP_LABELS: Record<string, string> = {
  left: "Αριστερή κάρτα",
  right: "Δεξιά κάρτα",
}

/** Human label for a key: the dictionary, else the key made readable. */
export function labelFor(key: string, group = false): string {
  if (group && GROUP_LABELS[key]) return GROUP_LABELS[key]
  if (FIELD_LABELS[key]) return FIELD_LABELS[key]
  return key
    .replace(/_/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .toLowerCase()
    .replace(/^./, (c) => c.toUpperCase())
}

const FIELD_ORDER = [
  "slug", "event", "org", "year", "subject",
  "eyebrow", "badge", "wordmark", "wordmarkAlt",
  "title", "heading", "headingLines", "name", "q", "label", "sub", "tagline",
  "taglinePre", "taglineAccent", "taglinePost", "hook", "lead",
  "description", "intro", "body", "text", "a", "quote", "excerpt", "paragraphs", "bold", "emphasis",
  "role", "category", "price", "value", "unit",
  "image", "imageAlt", "src", "alt", "photo", "avatar", "images", "gallery",
  "cta", "ctaLabel", "ctaPrimary", "ctaSecondary", "primary", "secondary", "link", "linkLabel", "linkHref", "href",
  "items", "links", "columns", "cards", "steps", "stats", "benefits",
]
const ORDER_INDEX = new Map(FIELD_ORDER.map((k, i) => [k, i]))

/** Sort keys into reading order: listed keys first, then the rest as given. */
export function orderKeys(keys: string[]): string[] {
  return keys
    .map((k, i) => [k, i] as const)
    .sort(([a, ai], [b, bi]) => (ORDER_INDEX.get(a) ?? 1000 + ai) - (ORDER_INDEX.get(b) ?? 1000 + bi))
    .map(([k]) => k)
}
