import type { ExecArgs } from "@medusajs/framework/types"
import {
  ContainerRegistrationKeys,
  Modules,
  ProductStatus,
} from "@medusajs/framework/utils"
import {
  createInventoryLevelsWorkflow,
  createProductCategoriesWorkflow,
  createProductsWorkflow,
  createTaxRegionsWorkflow,
  updateProductsWorkflow,
} from "@medusajs/medusa/core-flows"
import seedData from "./oros-products.json"

/**
 * Seed the OROS MACHAIRA honey catalogue into Medusa from the storefront's
 * static snapshot (generated by scripts/gen-medusa-seed.mts → oros-products.json).
 * Creates the 4 categories + 31 products (with per-size variants + EUR prices +
 * images + inventory), links them to the default sales channel, adds Cyprus &
 * Greece to the region, and removes the demo apparel products.
 *
 * Idempotent: skips products/categories that already exist. Re-run any time.
 *
 *   npx medusa exec ./src/scripts/seed-oros-products.ts
 */

const DEMO_HANDLES = ["t-shirt", "sweatshirt", "sweatpants", "shorts"]

export default async function seedOrosProducts({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const query = container.resolve(ContainerRegistrationKeys.QUERY)
  const regionService = container.resolve(Modules.REGION)

  // --- Base data (created by the initial seed; we reuse, never recreate) ------
  const { data: channels } = await query.graph({
    entity: "sales_channel",
    fields: ["id", "name"],
  })
  const salesChannel = channels[0]
  const { data: profiles } = await query.graph({
    entity: "shipping_profile",
    fields: ["id"],
  })
  const shippingProfile = profiles[0]
  const { data: locations } = await query.graph({
    entity: "stock_location",
    fields: ["id"],
  })
  const stockLocation = locations[0]
  if (!salesChannel || !shippingProfile || !stockLocation) {
    throw new Error(
      "Base commerce data missing (sales channel / shipping profile / stock location). Run the initial seed first."
    )
  }
  logger.info(`Using sales channel "${salesChannel.name}" (${salesChannel.id}).`)

  // --- Add Cyprus + Greece to the region (checkout ships there) ---------------
  const { data: regions } = await query.graph({
    entity: "region",
    fields: ["id", "name", "currency_code", "countries.iso_2"],
  })
  const region = regions.find((r) => r.currency_code === "eur") ?? regions[0]
  if (region) {
    const existing = (region.countries ?? [])
      .map((c) => c?.iso_2)
      .filter((x): x is string => !!x)
    const wanted = ["cy", "gr"].filter((c) => !existing.includes(c))
    if (wanted.length) {
      await regionService.updateRegions(region.id, {
        countries: [...existing, ...wanted],
      })
      try {
        await createTaxRegionsWorkflow(container).run({
          input: wanted.map((country_code) => ({ country_code, provider_id: "tp_system" })),
        })
      } catch (e) {
        logger.warn(`Tax region create skipped: ${(e as Error).message}`)
      }
      logger.info(`Added countries to region: ${wanted.join(", ")}.`)
    }
  }

  // --- Categories (idempotent) ------------------------------------------------
  const { data: existingCats } = await query.graph({
    entity: "product_category",
    fields: ["id", "name"],
  })
  const catByName = new Map<string, string>(
    existingCats.map((c: { id: string; name: string }) => [c.name, c.id])
  )
  const missingCats = seedData.categories.filter((n) => !catByName.has(n))
  if (missingCats.length) {
    const { result } = await createProductCategoriesWorkflow(container).run({
      input: { product_categories: missingCats.map((name) => ({ name, is_active: true })) },
    })
    for (const c of result) catByName.set(c.name, c.id)
    logger.info(`Created categories: ${missingCats.join(", ")}.`)
  }

  // --- Hide demo apparel (unpublish; can't delete — has stock reservations) ---
  const { data: demo } = await query.graph({
    entity: "product",
    fields: ["id", "handle", "status"],
    filters: { handle: DEMO_HANDLES },
  })
  const demoPublished = demo.filter((p) => p.status !== "draft")
  if (demoPublished.length) {
    await updateProductsWorkflow(container).run({
      input: {
        selector: { id: demoPublished.map((p) => p.id) },
        update: { status: ProductStatus.DRAFT },
      },
    })
    logger.info(`Unpublished ${demoPublished.length} demo product(s).`)
  }

  // --- Products (skip any that already exist) ---------------------------------
  const { data: existingProducts } = await query.graph({
    entity: "product",
    fields: ["handle"],
    filters: { handle: seedData.products.map((p) => p.handle) },
  })
  const have = new Set(existingProducts.map((p: { handle: string }) => p.handle))
  const toCreate = seedData.products.filter((p) => !have.has(p.handle))

  if (!toCreate.length) {
    logger.info("All products already seeded — nothing to create.")
    return
  }

  const productsInput = toCreate.map((p) => {
    const multi = p.variants.length > 1
    const options = multi
      ? [{ title: "Μέγεθος", values: p.variants.map((v) => v.size!) }]
      : [{ title: "Συσκευασία", values: ["Τεμάχιο"] }]

    return {
      title: p.title,
      handle: p.handle,
      description: p.description || undefined,
      status: ProductStatus.PUBLISHED,
      category_ids: catByName.has(p.category) ? [catByName.get(p.category)!] : [],
      shipping_profile_id: shippingProfile.id,
      sales_channels: [{ id: salesChannel.id }],
      thumbnail: p.thumbnail,
      images: p.images.map((url) => ({ url })),
      weight: 500,
      options,
      variants: p.variants.map((v) => ({
        title: v.title,
        sku: v.sku,
        manage_inventory: true,
        options: (multi
          ? { "Μέγεθος": v.size! }
          : { "Συσκευασία": "Τεμάχιο" }) as Record<string, string>,
        prices: [{ amount: v.amount, currency_code: "eur" }],
      })),
    }
  })

  logger.info(`Creating ${productsInput.length} products...`)
  await createProductsWorkflow(container).run({ input: { products: productsInput } })

  // --- Inventory levels (out-of-stock → 0, else plenty) -----------------------
  const outOfStock = new Set(toCreate.filter((p) => !p.inStock).map((p) => p.handle))
  const { data: created } = await query.graph({
    entity: "product",
    fields: ["handle", "variants.inventory_items.inventory_item_id"],
    filters: { handle: toCreate.map((p) => p.handle) },
  })

  const levels: {
    location_id: string
    inventory_item_id: string
    stocked_quantity: number
  }[] = []
  for (const p of created) {
    const qty = outOfStock.has(p.handle) ? 0 : 1000000
    for (const v of p.variants ?? []) {
      for (const ii of v.inventory_items ?? []) {
        if (ii?.inventory_item_id) {
          levels.push({
            location_id: stockLocation.id,
            inventory_item_id: ii.inventory_item_id,
            stocked_quantity: qty,
          })
        }
      }
    }
  }
  if (levels.length) {
    await createInventoryLevelsWorkflow(container).run({ input: { inventory_levels: levels } })
    logger.info(`Set ${levels.length} inventory levels (${outOfStock.size} products out of stock).`)
  }

  logger.info("✓ OROS MACHAIRA catalogue seeded.")
}
