// AUTO-GENERATED by scripts/awards-manifest.mjs — do not hand-edit.
// Award image paths + intrinsic dimensions (for masonry aspect ratios).
export type AwardImage = { src: string; w: number; h: number }
export const AWARD_IMAGES: Record<string, AwardImage[]> = {
  "cyprus-hospitality": [
    {
      "src": "/images/awards/cyprus-hospitality/01.webp?v=30182",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/02.webp?v=43664",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/03.webp?v=39216",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/04.webp?v=64154",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/05.webp?v=43870",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/06.webp?v=37234",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/07.webp?v=20206",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/08.webp?v=16906",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/09.webp?v=51914",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/10.webp?v=40116",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/11.webp?v=55700",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/12.webp?v=25266",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/13.webp?v=48540",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/14.webp?v=40858",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/15.webp?v=35906",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/16.webp?v=39490",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/17.webp?v=41512",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-hospitality/18.webp?v=35262",
      "w": 1200,
      "h": 910
    }
  ],
  "cyprus-tourism-2024": [
    {
      "src": "/images/awards/cyprus-tourism-2024/01.webp?v=94224",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-tourism-2024/02.webp?v=91804",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-tourism-2024/03.webp?v=109492",
      "w": 1200,
      "h": 909
    },
    {
      "src": "/images/awards/cyprus-tourism-2024/04.webp?v=56022",
      "w": 1200,
      "h": 910
    }
  ],
  "cyprus-tourism-2025": [
    {
      "src": "/images/awards/cyprus-tourism-2025/01.webp?v=55330",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-tourism-2025/02.webp?v=56976",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/cyprus-tourism-2025/03.webp?v=69830",
      "w": 1200,
      "h": 911
    }
  ],
  "excellent-taste-2025": [
    {
      "src": "/images/awards/excellent-taste-2025/01.webp?v=94632",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/excellent-taste-2025/02.webp?v=67544",
      "w": 1200,
      "h": 910
    }
  ],
  "ge-neo-epicheirein-2025": [
    {
      "src": "/images/awards/ge-neo-epicheirein-2025/01.webp?v=53436",
      "w": 1200,
      "h": 909
    },
    {
      "src": "/images/awards/ge-neo-epicheirein-2025/02.webp?v=69318",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/ge-neo-epicheirein-2025/03.webp?v=118096",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/ge-neo-epicheirein-2025/04.webp?v=45750",
      "w": 1200,
      "h": 910
    }
  ],
  "specialist-awards-2026": [
    {
      "src": "/images/awards/specialist-awards-2026/01.webp?v=87452",
      "w": 1200,
      "h": 910
    },
    {
      "src": "/images/awards/specialist-awards-2026/02.webp?v=11908",
      "w": 1200,
      "h": 910
    }
  ]
}
