/**
 * Blog category taxonomy (from WordPress). AUTO-GENERATED by _gencats.mjs.
 * Only categories that actually have articles are included.
 */

export type BlogCategory = { slug: string; name: string; count: number }

export const BLOG_CATEGORIES: BlogCategory[] = [
  {
    "slug": "arthra",
    "name": "Άρθρα",
    "count": 60
  },
  {
    "slug": "syntages-me-meli",
    "name": "Συνταγές με μέλι",
    "count": 11
  },
  {
    "slug": "fysi-kai-peripeteia",
    "name": "Φύση και Περιπέτεια",
    "count": 1
  },
  {
    "slug": "melissa-kai-perivallon",
    "name": "Μέλισσα και Περιβάλλον",
    "count": 1
  }
]

/** post slug -> the category slugs it belongs to */
export const POST_CATEGORIES: Record<string, string[]> = {
  "poy-na-agoraseis-agno-kypriako-meli-stin-kypro": [
    "arthra"
  ],
  "i-m-f-oros-maxaira-ltd-enischyei-ti-viosimotita-tis-me-exeidikeymeni-ypostirixi-kai-sygchrimatodotisi-tis-ee": [
    "arthra"
  ],
  "anaviosi-tis-kypriakis-aytochthonis-melissas-kainotomos-synergasia-gia-tin-diatirisi-kai-taytopoiisi-tis-fylis": [
    "arthra"
  ],
  "dipli-diakrisi-gia-to-oros-machaira-sta-cyprus-tourism-awards-2024": [
    "arthra"
  ],
  "melissochoria-kipros": [
    "fysi-kai-peripeteia"
  ],
  "yiothetiste-mia-kypseli": [
    "melissa-kai-perivallon"
  ],
  "fysika-proionta-ygieini-diatrofi-aloifes": [
    "arthra"
  ],
  "gemistes-glykopatates-me-meli-gia-mia-glykia-dosi-agapis-sto-deipno-ton-eroteymenon": [
    "syntages-me-meli"
  ],
  "spania-eidi-meliou": [
    "arthra"
  ],
  "poio-meli-einai-to-kalytero": [
    "arthra"
  ],
  "vasilissa-melissa": [
    "arthra"
  ],
  "mexikaniki-salata-me-vinegkret-kai-meli-oros-machaira": [
    "syntages-me-meli"
  ],
  "chtapodi-sti-ladokolla-me-skordo-meli-kai-valsamiko-2": [
    "syntages-me-meli"
  ],
  "spitiki-granola": [
    "syntages-me-meli"
  ],
  "solomos-me-meli-kai-piperoriza": [
    "syntages-me-meli"
  ],
  "salata-toy-cheimona": [
    "syntages-me-meli"
  ],
  "poytigka-sokolatas-a-la-ygieini-2": [
    "syntages-me-meli"
  ],
  "mpiskota-choris-psisimo-me-kinoa-amp-meli": [
    "syntages-me-meli"
  ],
  "kotopoylo-me-meli-kai-lemoni-2": [
    "syntages-me-meli"
  ],
  "garides-me-meli-kai-myrodika-2": [
    "syntages-me-meli"
  ],
  "vodino-steak-me-meli-amp-mpacharika": [
    "syntages-me-meli"
  ],
  "melomakarona-choris-katholoy-zachari": [
    "arthra"
  ],
  "voithise-mas-na-sosoyme-ti-melissa": [
    "arthra"
  ],
  "i-melissa-anakirychthike-to-pio-simantiko-emvio-on-ston-planiti": [
    "arthra"
  ],
  "tsizkeik-me-karydia-kai-gemisi-apo-tyri-kai-meli": [
    "arthra"
  ],
  "moys-melioy": [
    "arthra"
  ],
  "to-meli-oros-machaira-pistopoiimeno-me-to-sima-poiotitas-ton-organomenon-synolon-ton-melissokomon": [
    "arthra"
  ],
  "aleimma-me-meli-voytyro-kai-lemoni": [
    "arthra"
  ],
  "pagomeno-tsai-me-tzintzer-dyosmo-kai-meli": [
    "arthra"
  ],
  "7-ofeli-toy-melioy-gia-tin-epidermida-2": [
    "arthra"
  ],
  "loykoymades-me-manoyri-kai-meli": [
    "arthra"
  ],
  "ygieino-smoothie-me-kakao-mpanana-kai-meli": [
    "arthra"
  ],
  "drosero-fraoylenio-giaoyrti-me-meli": [
    "arthra"
  ],
  "meli-kai-skordo-poia-ta-ofeli": [
    "arthra"
  ],
  "pasteli-me-meli": [
    "arthra"
  ],
  "to-avrasto-meli": [
    "arthra"
  ],
  "mpoykies-me-karydia-soysami-kai-meli": [
    "arthra"
  ],
  "troyfakia-dimitriakon-me-meli-kai-tachini-me-kakao": [
    "arthra"
  ],
  "christoygenniatiki-galopoyla-me-meli": [
    "arthra"
  ],
  "meli-amp-kanela-oles-oi-therapeytikes-toys-idiotites": [
    "arthra"
  ],
  "spitiki-lemonada-me-meli-oros-machaira": [
    "arthra"
  ],
  "mpares-vromis-me-meli-oros-machaira": [
    "arthra"
  ],
  "maska-mallion-me-avokanto-kai-meli": [
    "arthra"
  ],
  "kaysi-lipoys-kai-ayxisi-myikis-mazas-taytochrona-katanalonontas-meli-kai-gyri": [
    "arthra"
  ],
  "garides-me-meli-kai-myrodika": [
    "arthra"
  ],
  "kotopoylo-me-meli-kai-lemoni": [
    "arthra"
  ],
  "poytigka-sokolatas-a-la-ygieini": [
    "arthra"
  ],
  "chtapodi-sti-ladokolla-me-skordo-meli-kai-valsamiko": [
    "arthra"
  ],
  "krystallosi-melioy-aitia-kai-lysi": [
    "arthra"
  ],
  "keik-me-meli-kai-vromi": [
    "arthra"
  ],
  "loykoymades-me-meli": [
    "arthra"
  ],
  "maska-enydatosis-meli-me-gala": [
    "arthra"
  ],
  "kokteil-me-mpananes-kai-meli": [
    "arthra"
  ],
  "giati-oi-melisses-pethainoyn-otan-mas-tsimpane": [
    "arthra"
  ],
  "maska-prosopoy-me-meli-kai-gala": [
    "arthra"
  ],
  "chymos-me-fraoyles-aktinidia-kai-meli": [
    "arthra"
  ],
  "7-kalokairina-kokteil-me-meli": [
    "arthra"
  ],
  "metaxenia-mallia-me-meli": [
    "arthra"
  ],
  "5-eyergetikes-idiotites-toy-melioy-stin-ygeia-mas": [
    "arthra"
  ],
  "pos-to-meli-tha-sas-exasfalisei-omorfo-kalokairi": [
    "arthra"
  ],
  "chaste-varos-me-meli-kai-kanela": [
    "arthra"
  ],
  "glasarismenos-solomos-me-meli-lachanika-kai-portokali": [
    "arthra"
  ],
  "ti-tha-symvei-an-exafanistoyn-oi-melisses": [
    "arthra"
  ],
  "ti-simainei-otan-krystallonei-to-meli": [
    "arthra"
  ],
  "poso-polytimo-einai-to-meli-gia-ti-zoi-mas": [
    "arthra"
  ],
  "7-therapeytikes-idiotites-toy-melioy": [
    "arthra"
  ],
  "7-ofeli-toy-melioy-gia-tin-epidermida": [
    "arthra"
  ],
  "meli-to-thaymatoyrgo-4-ofeli-toy-stin-ygeia-kai-tin-omorfia-sas": [
    "arthra"
  ],
  "psomi-meli-kai-kanela-ena-eyergetiko-proino-sti-nisteia": [
    "arthra"
  ],
  "poia-anthektika-mikrovia-katapolema-to-meli": [
    "arthra"
  ],
  "lemoni-kai-meli-gia-to-vicha": [
    "arthra"
  ],
  "gnoriste-tis-eyergetikes-idiotites-toy-melioy-gia-tin-ygeia-sas": [
    "arthra"
  ],
  "ti-einai-to-avrasto-meli": [
    "arthra"
  ]
}
