/**
 * Greek names of the visual editor's blocks — shared by the block registry
 * (blocks.tsx) and the admin's page summary (PuckField), which must not load
 * the whole registry.
 */
export const BLOCK_LABELS: Record<string, string> = {
  HeroPair: 'Κεντρικές κάρτες',
  TrustBadges: 'Εγγυήσεις',
  DealOfMonth: 'Τα Διαμάντια του Μαχαιρά',
  Ticker: 'Κυλιόμενη λωρίδα',
  ProductCategories: 'Κατηγορίες προϊόντων',
  AdoptHiveBanner: 'Υιοθετώ μια κυψέλη (banner)',
  Heritage: 'Η ιστορία μας',
  FlatlayBand: 'Προϊόντα στη φωτογραφία',
  BlogTeaser: 'Blog — πρόσφατα άρθρα',
  AboutHero: 'Κεντρική ενότητα',
  AboutStats: 'Αριθμοί',
  AboutValues: 'Αξίες',
  AboutIndoor: 'Εσωτερικοί χώροι',
  AboutOutdoor: 'Εξωτερικοί χώροι',
  AboutBand: 'Χρυσή λωρίδα κειμένου',
  AboutFamily: 'Η οικογένεια',
  AboutGoal: 'Ο στόχος μας (banner)',
  AdoptHero: 'Κεντρική ενότητα',
  AdoptIntro: 'Εισαγωγή & οφέλη',
  AdoptPartners: 'Συνεργάτες (λογότυπα)',
  AdoptPackage: 'Το πακέτο (βήματα)',
  GoalBand: 'Ο στόχος μας (βίντεο)',
  AdoptVisits: 'Οι επισκέψεις',
  AdoptGallery: 'Γκαλερί',
  AdoptProgress: 'Πρόοδος υιοθεσιών',
  AdoptTestimonials: 'Μαρτυρίες',
  AdoptFaq: 'Συχνές ερωτήσεις',
  AdoptCta: 'Κλείσιμο με φόρμα',
  ContactHero: 'Κεντρική εικόνα',
  ContactConnect: 'Στοιχεία & φόρμα επικοινωνίας',
  ContactMap: 'Χάρτης',
  ContactValues: 'Αξίες',
  ActivitiesHero: 'Κεντρική ενότητα με κουμπιά',
  ActivitiesExperiences: 'Εμπειρίες (κάρτες)',
  FactBand: 'Λωρίδα «Ήξερες ότι…»',
  ActivitiesPrograms: 'Προγράμματα (κάρτες)',
  PageHero: 'Κεντρική εικόνα με τίτλο',
  NatureStory: 'Εικόνα & κείμενο',
  NatureStats: 'Αριθμοί (λωρίδα)',
  NatureMatters: 'Εικόνα & κείμενο με έμφαση',
  CertificatesList: 'Πιστοποιητικά',
  AwardsHero: 'Κεντρική εικόνα (βραβεία)',
  AwardsList: 'Βραβεία',
  LegalDocument: 'Νομικό κείμενο',
}
